### ISSUE TITLE
Fix Screen serialization

### ISSUE THREAD

**Issue by rueberger** [ClandininLab/flystim#8]
[`Screen.serialize`](https://github.com/ClandininLab/flystim/blob/master/flystim/screen.py#L156) does not serialize the `azimuth` (previously rotation) and `offset` attributes which are required for reconstruction. 

Curiously, those same attributes where not even stored as attributes until recently. 

I believe the previous strategy was to represent the same information via tri-list. To me it feels more natural to serialize the more fundamental parameters of azimuth and offset and make tri-list a property

**Comment by rueberger** [comment]
Fixed in andrew-dev via https://github.com/ClandininLab/flystim/commit/c321a57b1dc31bd4c4c167bc7d9e6ff4786df0b9, 

which also includes a test-case for this scenario.

**Comment by mhturner** [comment]
This is fixed in the new screen / subscreen definitions using pa, pb, pc. Tri-list is gone now
